#pragma once 

#include <freya_base.h>
#include <freya_containers.h>
#include <freya_event.h>
#include <freya_logger.h>
#include <freya_memory.h>
#include <freya_window.h>
#include <freya_input.h>
#include <freya_math.h>
#include <freya_gfx.h>
#include <freya_threads.h>
#include <freya_audio.h>
#include <freya_timer.h>
#include <freya_ui.h>
#include <freya_file.h>
#include <freya_assets.h>
#include <freya_render.h>
#include <freya_app.h>
